default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  #port: 5433 # default port for postgresql is 5432
  username: omd
  password: omd

development:
  <<: *default
  database: omd_dev